name: resiliencia
description: "Sistema de diagnostico y recomendaciones para la ansiedad"
publish_to: 'none' 
version: 1.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3

  # State Management
  provider: ^6.1.2

  # HTTP Requests
  http: ^1.2.2

  # Almacenamiento local
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5

  # Encriptación
  encrypt: ^5.0.3
  crypto: ^3.0.3

  # Notificaciones locales
  flutter_local_notifications: ^19.5.0

  # URL Launcher
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/data/banco_recomendaciones.json